source "https://rubygems.org"

gem "json"
gem "jekyll"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-paginate"
# gem "jekyll-gist"
gem "jemoji"
# gem "jekyll-redirect-from"
gem "jekyll-mentions"
gem "jekyll-github-metadata"
